//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntonBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class TwitchEvent : global::System.Configuration.ApplicationSettingsBase {
        
        private static TwitchEvent defaultInstance = ((TwitchEvent)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TwitchEvent())));
        
        public static TwitchEvent Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOnline {
            get {
                return ((bool)(this["OnStreamOnline"]));
            }
            set {
                this["OnStreamOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOnlineChatText {
            get {
                return ((string)(this["OnStreamOnlineChatText"]));
            }
            set {
                this["OnStreamOnlineChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOnlineKonsoleText {
            get {
                return ((string)(this["OnStreamOnlineKonsoleText"]));
            }
            set {
                this["OnStreamOnlineKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOnlineDiscordText {
            get {
                return ((string)(this["OnStreamOnlineDiscordText"]));
            }
            set {
                this["OnStreamOnlineDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOffline {
            get {
                return ((bool)(this["OnStreamOffline"]));
            }
            set {
                this["OnStreamOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOfflineChatText {
            get {
                return ((string)(this["OnStreamOfflineChatText"]));
            }
            set {
                this["OnStreamOfflineChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOfflineKonsoleText {
            get {
                return ((string)(this["OnStreamOfflineKonsoleText"]));
            }
            set {
                this["OnStreamOfflineKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamOfflineDiscordText {
            get {
                return ((string)(this["OnStreamOfflineDiscordText"]));
            }
            set {
                this["OnStreamOfflineDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamUpdate {
            get {
                return ((bool)(this["OnStreamUpdate"]));
            }
            set {
                this["OnStreamUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamUpdateChatText {
            get {
                return ((string)(this["OnStreamUpdateChatText"]));
            }
            set {
                this["OnStreamUpdateChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamUpdateKonsoleText {
            get {
                return ((string)(this["OnStreamUpdateKonsoleText"]));
            }
            set {
                this["OnStreamUpdateKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnStreamUpdateDiscordText {
            get {
                return ((string)(this["OnStreamUpdateDiscordText"]));
            }
            set {
                this["OnStreamUpdateDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewFollowersDetected {
            get {
                return ((bool)(this["OnNewFollowersDetected"]));
            }
            set {
                this["OnNewFollowersDetected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewFollowersDetectedChatText {
            get {
                return ((string)(this["OnNewFollowersDetectedChatText"]));
            }
            set {
                this["OnNewFollowersDetectedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewFollowersDetectedKonsoleText {
            get {
                return ((string)(this["OnNewFollowersDetectedKonsoleText"]));
            }
            set {
                this["OnNewFollowersDetectedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewFollowersDetectedDiscordText {
            get {
                return ((string)(this["OnNewFollowersDetectedDiscordText"]));
            }
            set {
                this["OnNewFollowersDetectedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnMessageReceived {
            get {
                return ((bool)(this["OnMessageReceived"]));
            }
            set {
                this["OnMessageReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Die Reaktion auf einer Chat-Nachricht erfolgt über die Bot-Kommandos. Eine Einste" +
            "llung hier ist, außer die Aktivierung, nicht notwendig")]
        public string OnMessageReceivedChatText {
            get {
                return ((string)(this["OnMessageReceivedChatText"]));
            }
            set {
                this["OnMessageReceivedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Die Ausgabe würde bei vielen Nachrichten sehr schnell voll laufen, daher ist hier" +
            " keine Einstellung möglich")]
        public string OnMessageReceivedKonsoleText {
            get {
                return ((string)(this["OnMessageReceivedKonsoleText"]));
            }
            set {
                this["OnMessageReceivedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auf eine Twitch Nachricht, sollte am Besten auch auf Twitch reagiert werden und n" +
            "icht auf Discord")]
        public string OnMessageReceivedDiscordText {
            get {
                return ((string)(this["OnMessageReceivedDiscordText"]));
            }
            set {
                this["OnMessageReceivedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnWhisperReceived {
            get {
                return ((bool)(this["OnWhisperReceived"]));
            }
            set {
                this["OnWhisperReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Die Reaktion auf einer Chat-Nachricht erfolgt über die Bot-Kommandos. Eine Einste" +
            "llung hier ist, außer die Aktivierung, nicht notwendig")]
        public string OnWhisperReceivedChatText {
            get {
                return ((string)(this["OnWhisperReceivedChatText"]));
            }
            set {
                this["OnWhisperReceivedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Die Ausgabe würde bei vielen Nachrichten sehr schnell voll laufen, daher ist hier" +
            " keine Einstellung möglich")]
        public string OnWhisperReceivedKonsoleText {
            get {
                return ((string)(this["OnWhisperReceivedKonsoleText"]));
            }
            set {
                this["OnWhisperReceivedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auf eine Twitch Nachricht, sollte am Besten auch auf Twitch reagiert werden und n" +
            "icht auf Discord")]
        public string OnWhisperReceivedDiscordText {
            get {
                return ((string)(this["OnWhisperReceivedDiscordText"]));
            }
            set {
                this["OnWhisperReceivedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewSubscriber {
            get {
                return ((bool)(this["OnNewSubscriber"]));
            }
            set {
                this["OnNewSubscriber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewSubscriberChatText {
            get {
                return ((string)(this["OnNewSubscriberChatText"]));
            }
            set {
                this["OnNewSubscriberChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewSubscriberKonsoleText {
            get {
                return ((string)(this["OnNewSubscriberKonsoleText"]));
            }
            set {
                this["OnNewSubscriberKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnNewSubscriberDiscordText {
            get {
                return ((string)(this["OnNewSubscriberDiscordText"]));
            }
            set {
                this["OnNewSubscriberDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnConnected {
            get {
                return ((bool)(this["OnConnected"]));
            }
            set {
                this["OnConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnConnectedChatText {
            get {
                return ((string)(this["OnConnectedChatText"]));
            }
            set {
                this["OnConnectedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnConnectedKonsoleText {
            get {
                return ((string)(this["OnConnectedKonsoleText"]));
            }
            set {
                this["OnConnectedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnConnectedDiscordText {
            get {
                return ((string)(this["OnConnectedDiscordText"]));
            }
            set {
                this["OnConnectedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnBeingHosted {
            get {
                return ((bool)(this["OnBeingHosted"]));
            }
            set {
                this["OnBeingHosted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnBeingHostedChatText {
            get {
                return ((string)(this["OnBeingHostedChatText"]));
            }
            set {
                this["OnBeingHostedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnBeingHostedKonsoleText {
            get {
                return ((string)(this["OnBeingHostedKonsoleText"]));
            }
            set {
                this["OnBeingHostedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnBeingHostedDiscordText {
            get {
                return ((string)(this["OnBeingHostedDiscordText"]));
            }
            set {
                this["OnBeingHostedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidNotification {
            get {
                return ((bool)(this["OnRaidNotification"]));
            }
            set {
                this["OnRaidNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidNotificationChatText {
            get {
                return ((string)(this["OnRaidNotificationChatText"]));
            }
            set {
                this["OnRaidNotificationChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidNotificationKonsoleText {
            get {
                return ((string)(this["OnRaidNotificationKonsoleText"]));
            }
            set {
                this["OnRaidNotificationKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidNotificationDiscordText {
            get {
                return ((string)(this["OnRaidNotificationDiscordText"]));
            }
            set {
                this["OnRaidNotificationDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnJoinedChannel {
            get {
                return ((bool)(this["OnJoinedChannel"]));
            }
            set {
                this["OnJoinedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Das Event wird erzeugt, wenn sich der Bot an einem Channel verbindet. Diese Info " +
            "hat nichts im Chat zu suchen")]
        public string OnJoinedChannelChatText {
            get {
                return ((string)(this["OnJoinedChannelChatText"]));
            }
            set {
                this["OnJoinedChannelChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnJoinedChannelKonsoleText {
            get {
                return ((string)(this["OnJoinedChannelKonsoleText"]));
            }
            set {
                this["OnJoinedChannelKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Das Event wird erzeugt, wenn sich der Bot an einem Channel verbindet. Diese Info " +
            "hat nichts im Discord zu suchen")]
        public string OnJoinedChannelDiscordText {
            get {
                return ((string)(this["OnJoinedChannelDiscordText"]));
            }
            set {
                this["OnJoinedChannelDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserJoined {
            get {
                return ((bool)(this["OnUserJoined"]));
            }
            set {
                this["OnUserJoined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserJoinedChatText {
            get {
                return ((string)(this["OnUserJoinedChatText"]));
            }
            set {
                this["OnUserJoinedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserJoinedKonsoleText {
            get {
                return ((string)(this["OnUserJoinedKonsoleText"]));
            }
            set {
                this["OnUserJoinedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserJoinedDiscordText {
            get {
                return ((string)(this["OnUserJoinedDiscordText"]));
            }
            set {
                this["OnUserJoinedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnExistingUsersDetected {
            get {
                return ((bool)(this["OnExistingUsersDetected"]));
            }
            set {
                this["OnExistingUsersDetected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnExistingUsersDetectedChatText {
            get {
                return ((string)(this["OnExistingUsersDetectedChatText"]));
            }
            set {
                this["OnExistingUsersDetectedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnExistingUsersDetectedKonsoleText {
            get {
                return ((string)(this["OnExistingUsersDetectedKonsoleText"]));
            }
            set {
                this["OnExistingUsersDetectedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnExistingUsersDetectedDiscordText {
            get {
                return ((string)(this["OnExistingUsersDetectedDiscordText"]));
            }
            set {
                this["OnExistingUsersDetectedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnExistingUsersDetectedChat {
            get {
                return ((bool)(this["OnExistingUsersDetectedChat"]));
            }
            set {
                this["OnExistingUsersDetectedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnExistingUsersDetectedKonsole {
            get {
                return ((bool)(this["OnExistingUsersDetectedKonsole"]));
            }
            set {
                this["OnExistingUsersDetectedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnExistingUsersDetectedDiscord {
            get {
                return ((bool)(this["OnExistingUsersDetectedDiscord"]));
            }
            set {
                this["OnExistingUsersDetectedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserJoinedChat {
            get {
                return ((bool)(this["OnUserJoinedChat"]));
            }
            set {
                this["OnUserJoinedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserJoinedKonsole {
            get {
                return ((bool)(this["OnUserJoinedKonsole"]));
            }
            set {
                this["OnUserJoinedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserJoinedDiscord {
            get {
                return ((bool)(this["OnUserJoinedDiscord"]));
            }
            set {
                this["OnUserJoinedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnJoinedChannelChat {
            get {
                return ((bool)(this["OnJoinedChannelChat"]));
            }
            set {
                this["OnJoinedChannelChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnJoinedChannelKonsole {
            get {
                return ((bool)(this["OnJoinedChannelKonsole"]));
            }
            set {
                this["OnJoinedChannelKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnJoinedChannelDiscord {
            get {
                return ((bool)(this["OnJoinedChannelDiscord"]));
            }
            set {
                this["OnJoinedChannelDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidNotificationChat {
            get {
                return ((bool)(this["OnRaidNotificationChat"]));
            }
            set {
                this["OnRaidNotificationChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidNotificationKonsole {
            get {
                return ((bool)(this["OnRaidNotificationKonsole"]));
            }
            set {
                this["OnRaidNotificationKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidNotificationDiscord {
            get {
                return ((bool)(this["OnRaidNotificationDiscord"]));
            }
            set {
                this["OnRaidNotificationDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnBeingHostedChat {
            get {
                return ((bool)(this["OnBeingHostedChat"]));
            }
            set {
                this["OnBeingHostedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnBeingHostedKonsole {
            get {
                return ((bool)(this["OnBeingHostedKonsole"]));
            }
            set {
                this["OnBeingHostedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnBeingHostedDiscord {
            get {
                return ((bool)(this["OnBeingHostedDiscord"]));
            }
            set {
                this["OnBeingHostedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnConnectedChat {
            get {
                return ((bool)(this["OnConnectedChat"]));
            }
            set {
                this["OnConnectedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnConnectedKonsole {
            get {
                return ((bool)(this["OnConnectedKonsole"]));
            }
            set {
                this["OnConnectedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnConnectedDiscord {
            get {
                return ((bool)(this["OnConnectedDiscord"]));
            }
            set {
                this["OnConnectedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewSubscriberChat {
            get {
                return ((bool)(this["OnNewSubscriberChat"]));
            }
            set {
                this["OnNewSubscriberChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewSubscriberKonsole {
            get {
                return ((bool)(this["OnNewSubscriberKonsole"]));
            }
            set {
                this["OnNewSubscriberKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewSubscriberDiscord {
            get {
                return ((bool)(this["OnNewSubscriberDiscord"]));
            }
            set {
                this["OnNewSubscriberDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnWhisperReceivedChat {
            get {
                return ((bool)(this["OnWhisperReceivedChat"]));
            }
            set {
                this["OnWhisperReceivedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnWhisperReceivedKonsole {
            get {
                return ((bool)(this["OnWhisperReceivedKonsole"]));
            }
            set {
                this["OnWhisperReceivedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnWhisperReceivedDiscord {
            get {
                return ((bool)(this["OnWhisperReceivedDiscord"]));
            }
            set {
                this["OnWhisperReceivedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnMessageReceivedChat {
            get {
                return ((bool)(this["OnMessageReceivedChat"]));
            }
            set {
                this["OnMessageReceivedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnMessageReceivedKonsole {
            get {
                return ((bool)(this["OnMessageReceivedKonsole"]));
            }
            set {
                this["OnMessageReceivedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnMessageReceivedDiscord {
            get {
                return ((bool)(this["OnMessageReceivedDiscord"]));
            }
            set {
                this["OnMessageReceivedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewFollowersDetectedChat {
            get {
                return ((bool)(this["OnNewFollowersDetectedChat"]));
            }
            set {
                this["OnNewFollowersDetectedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewFollowersDetectedKonsole {
            get {
                return ((bool)(this["OnNewFollowersDetectedKonsole"]));
            }
            set {
                this["OnNewFollowersDetectedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnNewFollowersDetectedDiscord {
            get {
                return ((bool)(this["OnNewFollowersDetectedDiscord"]));
            }
            set {
                this["OnNewFollowersDetectedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamUpdateChat {
            get {
                return ((bool)(this["OnStreamUpdateChat"]));
            }
            set {
                this["OnStreamUpdateChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamUpdateKonsole {
            get {
                return ((bool)(this["OnStreamUpdateKonsole"]));
            }
            set {
                this["OnStreamUpdateKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamUpdateDiscord {
            get {
                return ((bool)(this["OnStreamUpdateDiscord"]));
            }
            set {
                this["OnStreamUpdateDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOfflineChat {
            get {
                return ((bool)(this["OnStreamOfflineChat"]));
            }
            set {
                this["OnStreamOfflineChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOfflineKonsole {
            get {
                return ((bool)(this["OnStreamOfflineKonsole"]));
            }
            set {
                this["OnStreamOfflineKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOfflineDiscord {
            get {
                return ((bool)(this["OnStreamOfflineDiscord"]));
            }
            set {
                this["OnStreamOfflineDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOnlineChat {
            get {
                return ((bool)(this["OnStreamOnlineChat"]));
            }
            set {
                this["OnStreamOnlineChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOnlineKonsole {
            get {
                return ((bool)(this["OnStreamOnlineKonsole"]));
            }
            set {
                this["OnStreamOnlineKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnStreamOnlineDiscord {
            get {
                return ((bool)(this["OnStreamOnlineDiscord"]));
            }
            set {
                this["OnStreamOnlineDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRewardRedeemed {
            get {
                return ((bool)(this["OnRewardRedeemed"]));
            }
            set {
                this["OnRewardRedeemed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRewardRedeemedChat {
            get {
                return ((bool)(this["OnRewardRedeemedChat"]));
            }
            set {
                this["OnRewardRedeemedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRewardRedeemedChatText {
            get {
                return ((string)(this["OnRewardRedeemedChatText"]));
            }
            set {
                this["OnRewardRedeemedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRewardRedeemedDiscord {
            get {
                return ((bool)(this["OnRewardRedeemedDiscord"]));
            }
            set {
                this["OnRewardRedeemedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRewardRedeemedDiscordText {
            get {
                return ((string)(this["OnRewardRedeemedDiscordText"]));
            }
            set {
                this["OnRewardRedeemedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRewardRedeemedKonsole {
            get {
                return ((bool)(this["OnRewardRedeemedKonsole"]));
            }
            set {
                this["OnRewardRedeemedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRewardRedeemedKonsoleText {
            get {
                return ((string)(this["OnRewardRedeemedKonsoleText"]));
            }
            set {
                this["OnRewardRedeemedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidGo {
            get {
                return ((bool)(this["OnRaidGo"]));
            }
            set {
                this["OnRaidGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidGoChat {
            get {
                return ((bool)(this["OnRaidGoChat"]));
            }
            set {
                this["OnRaidGoChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidGoChatText {
            get {
                return ((string)(this["OnRaidGoChatText"]));
            }
            set {
                this["OnRaidGoChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidGoDiscord {
            get {
                return ((bool)(this["OnRaidGoDiscord"]));
            }
            set {
                this["OnRaidGoDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidGoDiscordText {
            get {
                return ((string)(this["OnRaidGoDiscordText"]));
            }
            set {
                this["OnRaidGoDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnRaidGoKonsole {
            get {
                return ((bool)(this["OnRaidGoKonsole"]));
            }
            set {
                this["OnRaidGoKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnRaidGoKonsoleText {
            get {
                return ((string)(this["OnRaidGoKonsoleText"]));
            }
            set {
                this["OnRaidGoKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BitsReaction {
            get {
                return ((bool)(this["BitsReaction"]));
            }
            set {
                this["BitsReaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateTitleUse {
            get {
                return ((bool)(this["UpdateTitleUse"]));
            }
            set {
                this["UpdateTitleUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateTitleCommand {
            get {
                return ((string)(this["UpdateTitleCommand"]));
            }
            set {
                this["UpdateTitleCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateTitleChatText {
            get {
                return ((string)(this["UpdateTitleChatText"]));
            }
            set {
                this["UpdateTitleChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateTitleFailText {
            get {
                return ((string)(this["UpdateTitleFailText"]));
            }
            set {
                this["UpdateTitleFailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateTitleAdmin {
            get {
                return ((bool)(this["UpdateTitleAdmin"]));
            }
            set {
                this["UpdateTitleAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateTitleBroadcaster {
            get {
                return ((bool)(this["UpdateTitleBroadcaster"]));
            }
            set {
                this["UpdateTitleBroadcaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateGameUse {
            get {
                return ((bool)(this["UpdateGameUse"]));
            }
            set {
                this["UpdateGameUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateGameCommand {
            get {
                return ((string)(this["UpdateGameCommand"]));
            }
            set {
                this["UpdateGameCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateGameChatText {
            get {
                return ((string)(this["UpdateGameChatText"]));
            }
            set {
                this["UpdateGameChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateGameFailText {
            get {
                return ((string)(this["UpdateGameFailText"]));
            }
            set {
                this["UpdateGameFailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateGameAdmin {
            get {
                return ((bool)(this["UpdateGameAdmin"]));
            }
            set {
                this["UpdateGameAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateGameBoardcaster {
            get {
                return ((bool)(this["UpdateGameBoardcaster"]));
            }
            set {
                this["UpdateGameBoardcaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoRaidTextUse {
            get {
                return ((bool)(this["GoRaidTextUse"]));
            }
            set {
                this["GoRaidTextUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoRaidTextChat {
            get {
                return ((string)(this["GoRaidTextChat"]));
            }
            set {
                this["GoRaidTextChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoRaidTextFail {
            get {
                return ((string)(this["GoRaidTextFail"]));
            }
            set {
                this["GoRaidTextFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GoRaidTextAdmin {
            get {
                return ((bool)(this["GoRaidTextAdmin"]));
            }
            set {
                this["GoRaidTextAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GoRaidTextBroadcaster {
            get {
                return ((bool)(this["GoRaidTextBroadcaster"]));
            }
            set {
                this["GoRaidTextBroadcaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoRaidTextCommand {
            get {
                return ((string)(this["GoRaidTextCommand"]));
            }
            set {
                this["GoRaidTextCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SOUse {
            get {
                return ((bool)(this["SOUse"]));
            }
            set {
                this["SOUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SOChatText {
            get {
                return ((string)(this["SOChatText"]));
            }
            set {
                this["SOChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SOFailText {
            get {
                return ((string)(this["SOFailText"]));
            }
            set {
                this["SOFailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SOAdmin {
            get {
                return ((bool)(this["SOAdmin"]));
            }
            set {
                this["SOAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SOBoardcast {
            get {
                return ((bool)(this["SOBoardcast"]));
            }
            set {
                this["SOBoardcast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SOCommand {
            get {
                return ((string)(this["SOCommand"]));
            }
            set {
                this["SOCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnStreamOnlineChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnStreamOnlineChannel"]));
            }
            set {
                this["OnStreamOnlineChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserLeft {
            get {
                return ((bool)(this["OnUserLeft"]));
            }
            set {
                this["OnUserLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserLeftChat {
            get {
                return ((bool)(this["OnUserLeftChat"]));
            }
            set {
                this["OnUserLeftChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserLeftChatText {
            get {
                return ((string)(this["OnUserLeftChatText"]));
            }
            set {
                this["OnUserLeftChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserLeftDiscord {
            get {
                return ((bool)(this["OnUserLeftDiscord"]));
            }
            set {
                this["OnUserLeftDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserLeftDiscordText {
            get {
                return ((string)(this["OnUserLeftDiscordText"]));
            }
            set {
                this["OnUserLeftDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnUserLeftKonsole {
            get {
                return ((bool)(this["OnUserLeftKonsole"]));
            }
            set {
                this["OnUserLeftKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnUserLeftKonsoleText {
            get {
                return ((string)(this["OnUserLeftKonsoleText"]));
            }
            set {
                this["OnUserLeftKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnUserLeftChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnUserLeftChannel"]));
            }
            set {
                this["OnUserLeftChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnStreamOfflineChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnStreamOfflineChannel"]));
            }
            set {
                this["OnStreamOfflineChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnStreamUpdateChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnStreamUpdateChannel"]));
            }
            set {
                this["OnStreamUpdateChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnNewFollowersDetectedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnNewFollowersDetectedChannel"]));
            }
            set {
                this["OnNewFollowersDetectedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnMessageReceivedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnMessageReceivedChannel"]));
            }
            set {
                this["OnMessageReceivedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnWhisperReceivedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnWhisperReceivedChannel"]));
            }
            set {
                this["OnWhisperReceivedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnNewSubscriberChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnNewSubscriberChannel"]));
            }
            set {
                this["OnNewSubscriberChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnConnectedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnConnectedChannel"]));
            }
            set {
                this["OnConnectedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnBeingHostedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnBeingHostedChannel"]));
            }
            set {
                this["OnBeingHostedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnRaidNotificationChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnRaidNotificationChannel"]));
            }
            set {
                this["OnRaidNotificationChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnUserJoinedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnUserJoinedChannel"]));
            }
            set {
                this["OnUserJoinedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnExistingUsersDetectedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnExistingUsersDetectedChannel"]));
            }
            set {
                this["OnExistingUsersDetectedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnRewardRedeemedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnRewardRedeemedChannel"]));
            }
            set {
                this["OnRewardRedeemedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnRaidGoChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnRaidGoChannel"]));
            }
            set {
                this["OnRaidGoChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnJoinedChannelChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnJoinedChannelChannel"]));
            }
            set {
                this["OnJoinedChannelChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnClipCreated {
            get {
                return ((bool)(this["OnClipCreated"]));
            }
            set {
                this["OnClipCreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OnClipCreatedChannel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OnClipCreatedChannel"]));
            }
            set {
                this["OnClipCreatedChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnClipCreatedChat {
            get {
                return ((bool)(this["OnClipCreatedChat"]));
            }
            set {
                this["OnClipCreatedChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnClipCreatedChatText {
            get {
                return ((string)(this["OnClipCreatedChatText"]));
            }
            set {
                this["OnClipCreatedChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnClipCreatedDiscord {
            get {
                return ((bool)(this["OnClipCreatedDiscord"]));
            }
            set {
                this["OnClipCreatedDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnClipCreatedDiscordText {
            get {
                return ((string)(this["OnClipCreatedDiscordText"]));
            }
            set {
                this["OnClipCreatedDiscordText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnClipCreatedKonsole {
            get {
                return ((bool)(this["OnClipCreatedKonsole"]));
            }
            set {
                this["OnClipCreatedKonsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnClipCreatedKonsoleText {
            get {
                return ((string)(this["OnClipCreatedKonsoleText"]));
            }
            set {
                this["OnClipCreatedKonsoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClipCreateUse {
            get {
                return ((bool)(this["ClipCreateUse"]));
            }
            set {
                this["ClipCreateUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipCreateCommand {
            get {
                return ((string)(this["ClipCreateCommand"]));
            }
            set {
                this["ClipCreateCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipCreateChatText {
            get {
                return ((string)(this["ClipCreateChatText"]));
            }
            set {
                this["ClipCreateChatText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipCreateFailText {
            get {
                return ((string)(this["ClipCreateFailText"]));
            }
            set {
                this["ClipCreateFailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClipCreateAdmin {
            get {
                return ((bool)(this["ClipCreateAdmin"]));
            }
            set {
                this["ClipCreateAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClipCreateBoardcast {
            get {
                return ((bool)(this["ClipCreateBoardcast"]));
            }
            set {
                this["ClipCreateBoardcast"] = value;
            }
        }
    }
}
